// Generated by CoffeeScript 2.0.0
(function() {
  var assert, wget;

  wget = require('../index.js');

  assert = require('assert');

  it("should be able to get url", function(done) {
    new Promise(function(resolve) {
      return wget.wget('https://www.google.com/').then(function(result) {
        assert.ok(result);
        return resolve();
      });
    });
    return done();
  });

  it("should be able to get url sync", function(done) {
    var result;
    result = wget.wgetSync('https://www.google.com/');
    assert.ok(result);
    return done();
  });

}).call(this);
