// Generated by CoffeeScript 2.0.0
(function() {
  var needle, wget, wgetSync;

  needle = require("needle");

  wget = function(url) {
    return new Promise(function(resolve) {
      return needle.get(url, function(error, response) {
        if (!error && response.statusCode === 200) {
          return resolve(response.body);
        } else {
          throw new Error(error.message);
        }
      });
    });
  };

  wgetSync = async function(url) {
    var result;
    result = (await wget(url));
    return result;
  };

  exports.wget = wget;

  exports.wgetSync = wgetSync;

}).call(this);
